### ISSUE TITLE
Crear Ambiente de trabajo ERP PDR COLON  (Aplicacion Web)

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#10]
-

**Comment by pdrlcabeza** [comment]
Server de Colon

**Comment by pdrlcabeza** [comment]
Job: Consiste en 

- [ ] 
- [ ] Crear ambiente en el servidor
- [ ] Clonar base de datos
- [ ] Clonar y restaurar ambientes de reportes
- [ ] Establecer procesos almacenados individuales para la instancia
- [ ] Pruebas de funcionamiento
- [ ] Asignar puertoy desplegar en Intranet
- [ ] Comunicacion a los usuarios
- [ ] Creacion de usuarios y roles
- [ ] Solucion de problemas
