### ISSUE TITLE
ERP - Payment Process (Implementación)

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#14]

**Comment by pdrlcabeza** [comment]
#Job: El proceso de pago se compone de 2 item, Pagos de facturas y abonos al proveedor.
Trabajando en esta implementacion veo que primero hay que definir:

- [x] A partir de que factura inician los pagos por el sistema ERP
- [ ] Cual es el correcto proceso de aplicacion de abonos
- [ ] Proceso correcto de entrega de abonos al proveedor y su debido cruce con facturas.

Estos temas  apesar de haber sido pre-conversado no se han aterrizado en papel y es importante definirlos.
