### ISSUE TITLE
ERP Version 1

### ISSUE THREAD

**Issue by pdrlcabeza** [jdpalermo/Software-Development#15]
Esta primera version abarca modulos que ya se han venido utilizando y modulos nuevos a desarrollar, buscamos tener los siguientes modulos:

- [x] Programacion de ajustes visuales y logica sencilla
- [x] Creación de personas
- [x] Creación de clientes
- [x] Creación de proveedores
- [x] Creación de contrato de (compra-venta, hipoteca)
- [x] Manejo de la deuda del cliente
- [x] Manejo de los pagos del cliente
- [x] Manejo de estados de cuenta
- [x] Modulo de pagos en caja de letras y facturas.
- [x] Manejo de productos
- [x] Inventario simple
- [x] Ajustes de inventario
- [x] Ordenes de compra
- [x] Recepcion de productos
- [x] Facturacion de proveedores
- [x] Pagos y abonos de proveedores
Cotizacion y pedidos de cliente
Factura de ventas de productos de clientes
- [x] Reportes automaticos
- [x] Smartchat
- [x] Kanban
- [x] Attachments
- [x] Firmado digital

**Comment by pdrlcabeza** [comment]
Esta primera version abarca modulos que ya se han venido utilizando y modulos nuevos a desarrollar, buscamos tener los siguientes modulos:

1. Creación de personas
2. Creación de clientes
3. Creación de proveedores
4. Creación de contrato de (compra-venta, hipoteca)
5. Manejo de la deuda del cliente
6. Manejo de los pagos del cliente
7. Manejo de estados de cuenta
8. Modulo de pagos en caja de letras y facturas.
9. Manejo de productos
10. Inventario
11. Ordenes de compra
12. Recepcion de productos
13. Facturacion de  proveedores
14. Pagos y abonos de proveedores
15. Cotizacion y pedidos de cliente
16. factura de ventas de productos de clientes

**Comment by pdrlcabeza** [comment]
@jdpalermo Para mi finalizada lam primera version
